---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    dapr.io/app-id: dynamic-flow-app
    dapr.io/enable-api-logging: 'true'
    dapr.io/enabled: 'true'
    k8s.kuboard.cn/name: dynamic-flow
  name: dynamic-flow
  namespace: dapr
  resourceVersion: '1341347'
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      dapr.io/app-id: dynamic-flow-app
      dapr.io/enable-api-logging: 'true'
      dapr.io/enabled: 'true'
      k8s.kuboard.cn/name: dynamic-flow
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        dapr.io/app-id: dynamic-flow-app
        dapr.io/enable-api-logging: 'true'
        dapr.io/enabled: 'true'
        k8s.kuboard.cn/name: dynamic-flow
    spec:
      containers:
        - image: 'docker-registry.zero.internal/dynamic-flow:latest'
          imagePullPolicy: Always
          name: dynamic-flow
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    dapr.io/app-id: dynamic-flow-app
    dapr.io/enable-api-logging: 'true'
    dapr.io/enabled: 'true'
    k8s.kuboard.cn/name: dynamic-flow
  name: dynamic-flow
  namespace: dapr
  resourceVersion: '1341532'
spec:
  clusterIP: 10.105.91.77
  clusterIPs:
    - 10.105.91.77
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    dapr.io/app-id: dynamic-flow-app
    dapr.io/enable-api-logging: 'true'
    dapr.io/enabled: 'true'
    k8s.kuboard.cn/name: dynamic-flow
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {}
  labels:
    dapr.io/app-id: dynamic-flow-app
    dapr.io/enable-api-logging: 'true'
    dapr.io/enabled: 'true'
    k8s.kuboard.cn/name: dynamic-flow
  name: dynamic-flow
  namespace: dapr
  resourceVersion: '1341550'
spec:
  ingressClassName: nginx
  rules:
    - host: flow.zero.internal
      http:
        paths:
          - backend:
              service:
                name: dynamic-flow
                port:
                  number: 8080
            path: /
            pathType: Prefix

