apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mongo-dapr
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: server
    value: mongo-mongodb
  - name: host
    value: mongo-mongodb:27017
  - name: password
    secretKeyRef:
      name: 'mongo-mongodb'
      key: 'mongodb-root-password'
  - name: databaseName
    value: dynamic-flow
